//! AUTO-GENERATED by scripts/regenerate_metadata_registry.py — do not edit by hand.
//! Re-run: `python scripts/regenerate_metadata_registry.py`

use super::metadata::IndicatorMetadata;

use crate::indicators::adaptive_ema::ADAPTIVE_EMA_METADATA;
use crate::indicators::alligator::ALLIGATOR_METADATA;
use crate::indicators::alma::ALMA_METADATA;
use crate::indicators::amfm::AM_DETECTOR_METADATA;
use crate::indicators::amfm::FM_DEMODULATOR_METADATA;
use crate::indicators::atr_ts::ATR_TS_METADATA;
use crate::indicators::autotune::AUTOTUNE_FILTER_METADATA;
use crate::indicators::bandpass::BANDPASS_METADATA;
use crate::indicators::butterworth::BUTTERWORTH2_METADATA;
use crate::indicators::butterworth::BUTTERWORTH3_METADATA;
use crate::indicators::cg::CG_METADATA;
use crate::indicators::channel_cycle::CHANNEL_CYCLE_METADATA;
use crate::indicators::choppiness_index::CHOPPINESS_INDEX_METADATA;
use crate::indicators::classic_laguerre::CLASSIC_LAGUERRE_METADATA;
use crate::indicators::continuation_index::CONTINUATION_INDEX_METADATA;
use crate::indicators::correlation_cycle::CORRELATION_CYCLE_METADATA;
use crate::indicators::correlation_trend::CORRELATION_TREND_METADATA;
use crate::indicators::cyber_cycle::CYBER_CYCLE_METADATA;
use crate::indicators::cybernetic_oscillator::CYBERNETIC_OSCILLATOR_METADATA;
use crate::indicators::cycle::HT_DCPERIOD_METADATA;
use crate::indicators::cycle::HT_DCPHASE_METADATA;
use crate::indicators::cycle::HT_PHASOR_METADATA;
use crate::indicators::cycle::HT_SINE_METADATA;
use crate::indicators::cycle::HT_TRENDMODE_METADATA;
use crate::indicators::cycle_trend_analytics::CYCLE_TREND_ANALYTICS_METADATA;
use crate::indicators::dmh::DMH_METADATA;
use crate::indicators::donchian::DONCHIAN_METADATA;
use crate::indicators::dsma::DSMA_METADATA;
use crate::indicators::ehlers_autocorrelation::EHLERS_AUTOCORRELATION_METADATA;
use crate::indicators::ehlers_filter::EHLERS_FILTER_METADATA;
use crate::indicators::ehlers_loops::EHLERS_LOOPS_METADATA;
use crate::indicators::ehlers_stochastic::EHLERS_STOCHASTIC_METADATA;
use crate::indicators::ehlers_ultimate_oscillator::EHLERS_ULTIMATE_OSCILLATOR_METADATA;
use crate::indicators::emd::EMD_METADATA;
use crate::indicators::fisher::FISHER_METADATA;
use crate::indicators::fisher_high_pass::FISHER_HIGH_PASS_METADATA;
use crate::indicators::fourier_series::FOURIER_SERIES_MODEL_METADATA;
use crate::indicators::fourier_transform::FOURIER_DOMINANT_CYCLE_METADATA;
use crate::indicators::fractals::FRACTALS_METADATA;
use crate::indicators::frama::FRAMA_METADATA;
use crate::indicators::gap_momentum::GAP_MOMENTUM_METADATA;
use crate::indicators::gaussian::GAUSSIAN_FILTER_METADATA;
use crate::indicators::generalized_laguerre::GENERALIZED_LAGUERRE_METADATA;
use crate::indicators::geometric_patterns::GEOMETRIC_PATTERNS_METADATA;
use crate::indicators::griffiths_dominant_cycle::GRIFFITHS_DOMINANT_CYCLE_METADATA;
use crate::indicators::griffiths_predictor::GRIFFITHS_PREDICTOR_METADATA;
use crate::indicators::griffiths_spectrum::GRIFFITHS_SPECTRUM_METADATA;
use crate::indicators::hamming::HAMMING_FILTER_METADATA;
use crate::indicators::hann::HANN_FILTER_METADATA;
use crate::indicators::harrington_adx::HARRINGTON_ADX_METADATA;
use crate::indicators::heikin_ashi::HEIKIN_ASHI_METADATA;
use crate::indicators::high_pass::HIGH_PASS_METADATA;
use crate::indicators::hma::HMA_METADATA;
use crate::indicators::homodyne_discriminator::HOMODYNE_DISCRIMINATOR_METADATA;
use crate::indicators::hurst::HURST_EXPONENT_METADATA;
use crate::indicators::ichimoku::ICHIMOKU_METADATA;
use crate::indicators::instantaneous_trendline::INSTANTANEOUS_TRENDLINE_METADATA;
use crate::indicators::inverse_fisher::INVERSE_FISHER_METADATA;
use crate::indicators::just_ignore_them::UNDERSAMPLED_DOUBLE_MA_METADATA;
use crate::indicators::kalman::KALMAN_FILTER_METADATA;
use crate::indicators::kama::KAMA_METADATA;
use crate::indicators::keltner::KELTNER_METADATA;
use crate::indicators::kinematic_kalman::KINEMATIC_KALMAN_METADATA;
use crate::indicators::laguerre_filter::LAGUERRE_FILTER_METADATA;
use crate::indicators::laguerre_oscillator::LAGUERRE_OSCILLATOR_METADATA;
use crate::indicators::laguerre_rsi::LAGUERRE_RSI_METADATA;
use crate::indicators::mad::MAD_METADATA;
use crate::indicators::madh::MADH_METADATA;
use crate::indicators::mama::MAMA_METADATA;
use crate::indicators::market_state::MARKET_STATE_METADATA;
use crate::indicators::market_structure::MARKET_STRUCTURE_METADATA;
use crate::indicators::mesa_stochastic::MESA_STOCHASTIC_METADATA;
use crate::indicators::momentum::ADX_METADATA;
use crate::indicators::momentum::APO_METADATA;
use crate::indicators::momentum::AROON_METADATA;
use crate::indicators::momentum::CCI_METADATA;
use crate::indicators::momentum::CMO_METADATA;
use crate::indicators::momentum::MACD_METADATA;
use crate::indicators::momentum::MFI_METADATA;
use crate::indicators::momentum::MOM_METADATA;
use crate::indicators::momentum::PPO_METADATA;
use crate::indicators::momentum::ROC_METADATA;
use crate::indicators::momentum::RSI_METADATA;
use crate::indicators::momentum::STOCH_METADATA;
use crate::indicators::momentum::TRIX_METADATA;
use crate::indicators::momentum::ULTOSC_METADATA;
use crate::indicators::momentum::WILLR_METADATA;
use crate::indicators::my_rsi::MY_RSI_METADATA;
use crate::indicators::noise_elimination::NOISE_ELIMINATION_METADATA;
use crate::indicators::oc_price_rsi::OC_PRICE_RSI_METADATA;
use crate::indicators::one_euro_filter::ONE_EURO_FILTER_METADATA;
use crate::indicators::overlap::BBANDS_METADATA;
use crate::indicators::overlap::DEMA_METADATA;
use crate::indicators::overlap::SAR_METADATA;
use crate::indicators::overlap::T3_METADATA;
use crate::indicators::overlap::TRIMA_METADATA;
use crate::indicators::pairs_rotation::PAIRS_ROTATION_METADATA;
use crate::indicators::pattern::CDL2CROWS_METADATA;
use crate::indicators::pattern::CDL3BLACKCROWS_METADATA;
use crate::indicators::pattern::CDL3INSIDE_METADATA;
use crate::indicators::pattern::CDL3LINESTRIKE_METADATA;
use crate::indicators::pattern::CDL3OUTSIDE_METADATA;
use crate::indicators::pattern::CDL3STARSINSOUTH_METADATA;
use crate::indicators::pattern::CDL3WHITESOLDIERS_METADATA;
use crate::indicators::pattern::CDLABANDONEDBABY_METADATA;
use crate::indicators::pattern::CDLADVANCEBLOCK_METADATA;
use crate::indicators::pattern::CDLBELTHOLD_METADATA;
use crate::indicators::pattern::CDLBREAKAWAY_METADATA;
use crate::indicators::pattern::CDLCLOSINGMARUBOZU_METADATA;
use crate::indicators::pattern::CDLCONCEALBABYSWALL_METADATA;
use crate::indicators::pattern::CDLCOUNTERATTACK_METADATA;
use crate::indicators::pattern::CDLDARKCLOUDCOVER_METADATA;
use crate::indicators::pattern::CDLDOJISTAR_METADATA;
use crate::indicators::pattern::CDLDOJI_METADATA;
use crate::indicators::pattern::CDLDRAGONFLYDOJI_METADATA;
use crate::indicators::pattern::CDLENGULFING_METADATA;
use crate::indicators::pattern::CDLEVENINGDOJISTAR_METADATA;
use crate::indicators::pattern::CDLEVENINGSTAR_METADATA;
use crate::indicators::pattern::CDLGAPSIDESIDEWHITE_METADATA;
use crate::indicators::pattern::CDLGRAVESTONEDOJI_METADATA;
use crate::indicators::pattern::CDLHAMMER_METADATA;
use crate::indicators::pattern::CDLHANGINGMAN_METADATA;
use crate::indicators::pattern::CDLHARAMICROSS_METADATA;
use crate::indicators::pattern::CDLHARAMI_METADATA;
use crate::indicators::pattern::CDLHIGHWAVE_METADATA;
use crate::indicators::pattern::CDLHIKKAKEMOD_METADATA;
use crate::indicators::pattern::CDLHIKKAKE_METADATA;
use crate::indicators::pattern::CDLHOMINGPIGEON_METADATA;
use crate::indicators::pattern::CDLIDENTICAL3CROWS_METADATA;
use crate::indicators::pattern::CDLINNECK_METADATA;
use crate::indicators::pattern::CDLINVERTEDHAMMER_METADATA;
use crate::indicators::pattern::CDLKICKINGBYLENGTH_METADATA;
use crate::indicators::pattern::CDLKICKING_METADATA;
use crate::indicators::pattern::CDLLADDERBOTTOM_METADATA;
use crate::indicators::pattern::CDLLONGLEGGEDDOJI_METADATA;
use crate::indicators::pattern::CDLLONGLINE_METADATA;
use crate::indicators::pattern::CDLMARUBOZU_METADATA;
use crate::indicators::pattern::CDLMATCHINGLOW_METADATA;
use crate::indicators::pattern::CDLMATHOLD_METADATA;
use crate::indicators::pattern::CDLMORNINGDOJISTAR_METADATA;
use crate::indicators::pattern::CDLMORNINGSTAR_METADATA;
use crate::indicators::pattern::CDLONNECK_METADATA;
use crate::indicators::pattern::CDLPIERCING_METADATA;
use crate::indicators::pattern::CDLRICKSHAWMAN_METADATA;
use crate::indicators::pattern::CDLRISEFALL3METHODS_METADATA;
use crate::indicators::pattern::CDLSEPARATINGLINES_METADATA;
use crate::indicators::pattern::CDLSHOOTINGSTAR_METADATA;
use crate::indicators::pattern::CDLSHORTLINE_METADATA;
use crate::indicators::pattern::CDLSPINNINGTOP_METADATA;
use crate::indicators::pattern::CDLSTALLEDPATTERN_METADATA;
use crate::indicators::pattern::CDLSTICKSANDWICH_METADATA;
use crate::indicators::pattern::CDLTAKURI_METADATA;
use crate::indicators::pattern::CDLTASUKIGAP_METADATA;
use crate::indicators::pattern::CDLTHRUSTING_METADATA;
use crate::indicators::pattern::CDLTRISTAR_METADATA;
use crate::indicators::pattern::CDLUNIQUE3RIVER_METADATA;
use crate::indicators::pattern::CDLUPSIDEGAP2CROWS_METADATA;
use crate::indicators::pattern::CDLXSIDEGAP3METHODS_METADATA;
use crate::indicators::phasor::PHASOR_METADATA;
use crate::indicators::pivot_points::PIVOT_POINTS_METADATA;
use crate::indicators::pma::PROJECTED_MOVING_AVERAGE_METADATA;
use crate::indicators::precision_trend::PRECISION_TREND_ANALYSIS_METADATA;
use crate::indicators::price_transform::AVGPRICE_METADATA;
use crate::indicators::price_transform::MEDPRICE_METADATA;
use crate::indicators::price_transform::OC2_METADATA;
use crate::indicators::price_transform::TYPPRICE_METADATA;
use crate::indicators::price_transform::WCLPRICE_METADATA;
use crate::indicators::recursive_median::RECURSIVE_MEDIAN_METADATA;
use crate::indicators::recursive_median::RECURSIVE_MEDIAN_OSCILLATOR_METADATA;
use crate::indicators::reflex::REFLEX_METADATA;
use crate::indicators::reverse_ema::REVERSE_EMA_METADATA;
use crate::indicators::reversion_index::REVERSION_INDEX_METADATA;
use crate::indicators::rocket_rsi::ROCKET_RSI_METADATA;
use crate::indicators::roofing_filter::ROOFING_FILTER_METADATA;
use crate::indicators::rsih::RSIH_METADATA;
use crate::indicators::sdo::SDO_METADATA;
use crate::indicators::simple_predictor::SIMPLE_PREDICTOR_METADATA;
use crate::indicators::sine_wave::SINE_WAVE_METADATA;
use crate::indicators::smoothing::EMA_METADATA;
use crate::indicators::smoothing::SMA_METADATA;
use crate::indicators::smoothing::WMA_METADATA;
use crate::indicators::sr_monitor::SR_INTERACTION_MONITOR_METADATA;
use crate::indicators::statistics::BETA_METADATA;
use crate::indicators::statistics::CORREL_METADATA;
use crate::indicators::statistics::LINREG_METADATA;
use crate::indicators::statistics::STDDEV_METADATA;
use crate::indicators::stc::STC_METADATA;
use crate::indicators::super_smoother::SUPER_SMOOTHER_METADATA;
use crate::indicators::swiss_army_knife::SWISS_ARMY_KNIFE_METADATA;
use crate::indicators::synthetic_oscillator::SYNTHETIC_OSCILLATOR_METADATA;
use crate::indicators::system_evaluator::SYSTEM_EVALUATOR_METADATA;
use crate::indicators::tema::TEMA_METADATA;
use crate::indicators::tema::ZLEMA_METADATA;
use crate::indicators::tradj_ema::TRADJ_EMA_METADATA;
use crate::indicators::trendflex::TRENDFLEX_METADATA;
use crate::indicators::triangle::TRIANGLE_FILTER_METADATA;
use crate::indicators::truncated_bandpass::TRUNCATED_BANDPASS_METADATA;
use crate::indicators::ttm_squeeze::TTM_SQUEEZE_METADATA;
use crate::indicators::ultimate_bands::ULTIMATE_BANDS_METADATA;
use crate::indicators::ultimate_channel::ULTIMATE_CHANNEL_METADATA;
use crate::indicators::ultimate_smoother::ULTIMATE_SMOOTHER_METADATA;
use crate::indicators::universal_oscillator::UNIVERSAL_OSCILLATOR_METADATA;
use crate::indicators::usi::USI_METADATA;
use crate::indicators::volatility::ATR_METADATA;
use crate::indicators::volatility::NATR_METADATA;
use crate::indicators::volatility::TRUE_RANGE_METADATA;
use crate::indicators::volume::ADOSC_METADATA;
use crate::indicators::volume::AD_METADATA;
use crate::indicators::volume::OBV_METADATA;
use crate::indicators::volume_profile::VOLUME_PROFILE_METADATA;
use crate::indicators::vortex::VORTEX_METADATA;
use crate::indicators::voss_predictor::VOSS_PREDICTOR_METADATA;
use crate::indicators::vpn::VPN_METADATA;
use crate::indicators::vwap::VWAP_METADATA;
use crate::indicators::wavetrend::WAVETREND_METADATA;
use crate::indicators::zero_lag::ZERO_LAG_METADATA;

/// Slug + metadata pair for codegen and discovery.
#[derive(Debug, Clone, Copy)]
pub struct RegisteredMetadata {
    pub slug: &'static str,
    pub meta: &'static IndicatorMetadata,
}

/// All registered indicator metadata (slug is Python/API key derived from const name).
pub static ALL_REGISTERED: &[RegisteredMetadata] = &[
    RegisteredMetadata { slug: "adaptive_ema", meta: &ADAPTIVE_EMA_METADATA },
    RegisteredMetadata { slug: "adosc", meta: &ADOSC_METADATA },
    RegisteredMetadata { slug: "adx", meta: &ADX_METADATA },
    RegisteredMetadata { slug: "ad", meta: &AD_METADATA },
    RegisteredMetadata { slug: "alligator", meta: &ALLIGATOR_METADATA },
    RegisteredMetadata { slug: "alma", meta: &ALMA_METADATA },
    RegisteredMetadata { slug: "am_detector", meta: &AM_DETECTOR_METADATA },
    RegisteredMetadata { slug: "apo", meta: &APO_METADATA },
    RegisteredMetadata { slug: "aroon", meta: &AROON_METADATA },
    RegisteredMetadata { slug: "atr", meta: &ATR_METADATA },
    RegisteredMetadata { slug: "atr_ts", meta: &ATR_TS_METADATA },
    RegisteredMetadata { slug: "autotune_filter", meta: &AUTOTUNE_FILTER_METADATA },
    RegisteredMetadata { slug: "avgprice", meta: &AVGPRICE_METADATA },
    RegisteredMetadata { slug: "bandpass", meta: &BANDPASS_METADATA },
    RegisteredMetadata { slug: "bbands", meta: &BBANDS_METADATA },
    RegisteredMetadata { slug: "beta", meta: &BETA_METADATA },
    RegisteredMetadata { slug: "butterworth2", meta: &BUTTERWORTH2_METADATA },
    RegisteredMetadata { slug: "butterworth3", meta: &BUTTERWORTH3_METADATA },
    RegisteredMetadata { slug: "cci", meta: &CCI_METADATA },
    RegisteredMetadata { slug: "cdl2crows", meta: &CDL2CROWS_METADATA },
    RegisteredMetadata { slug: "cdl3blackcrows", meta: &CDL3BLACKCROWS_METADATA },
    RegisteredMetadata { slug: "cdl3inside", meta: &CDL3INSIDE_METADATA },
    RegisteredMetadata { slug: "cdl3linestrike", meta: &CDL3LINESTRIKE_METADATA },
    RegisteredMetadata { slug: "cdl3outside", meta: &CDL3OUTSIDE_METADATA },
    RegisteredMetadata { slug: "cdl3starsinsouth", meta: &CDL3STARSINSOUTH_METADATA },
    RegisteredMetadata { slug: "cdl3whitesoldiers", meta: &CDL3WHITESOLDIERS_METADATA },
    RegisteredMetadata { slug: "cdlabandonedbaby", meta: &CDLABANDONEDBABY_METADATA },
    RegisteredMetadata { slug: "cdladvanceblock", meta: &CDLADVANCEBLOCK_METADATA },
    RegisteredMetadata { slug: "cdlbelthold", meta: &CDLBELTHOLD_METADATA },
    RegisteredMetadata { slug: "cdlbreakaway", meta: &CDLBREAKAWAY_METADATA },
    RegisteredMetadata { slug: "cdlclosingmarubozu", meta: &CDLCLOSINGMARUBOZU_METADATA },
    RegisteredMetadata { slug: "cdlconcealbabyswall", meta: &CDLCONCEALBABYSWALL_METADATA },
    RegisteredMetadata { slug: "cdlcounterattack", meta: &CDLCOUNTERATTACK_METADATA },
    RegisteredMetadata { slug: "cdldarkcloudcover", meta: &CDLDARKCLOUDCOVER_METADATA },
    RegisteredMetadata { slug: "cdldojistar", meta: &CDLDOJISTAR_METADATA },
    RegisteredMetadata { slug: "cdldoji", meta: &CDLDOJI_METADATA },
    RegisteredMetadata { slug: "cdldragonflydoji", meta: &CDLDRAGONFLYDOJI_METADATA },
    RegisteredMetadata { slug: "cdlengulfing", meta: &CDLENGULFING_METADATA },
    RegisteredMetadata { slug: "cdleveningdojistar", meta: &CDLEVENINGDOJISTAR_METADATA },
    RegisteredMetadata { slug: "cdleveningstar", meta: &CDLEVENINGSTAR_METADATA },
    RegisteredMetadata { slug: "cdlgapsidesidewhite", meta: &CDLGAPSIDESIDEWHITE_METADATA },
    RegisteredMetadata { slug: "cdlgravestonedoji", meta: &CDLGRAVESTONEDOJI_METADATA },
    RegisteredMetadata { slug: "cdlhammer", meta: &CDLHAMMER_METADATA },
    RegisteredMetadata { slug: "cdlhangingman", meta: &CDLHANGINGMAN_METADATA },
    RegisteredMetadata { slug: "cdlharamicross", meta: &CDLHARAMICROSS_METADATA },
    RegisteredMetadata { slug: "cdlharami", meta: &CDLHARAMI_METADATA },
    RegisteredMetadata { slug: "cdlhighwave", meta: &CDLHIGHWAVE_METADATA },
    RegisteredMetadata { slug: "cdlhikkakemod", meta: &CDLHIKKAKEMOD_METADATA },
    RegisteredMetadata { slug: "cdlhikkake", meta: &CDLHIKKAKE_METADATA },
    RegisteredMetadata { slug: "cdlhomingpigeon", meta: &CDLHOMINGPIGEON_METADATA },
    RegisteredMetadata { slug: "cdlidentical3crows", meta: &CDLIDENTICAL3CROWS_METADATA },
    RegisteredMetadata { slug: "cdlinneck", meta: &CDLINNECK_METADATA },
    RegisteredMetadata { slug: "cdlinvertedhammer", meta: &CDLINVERTEDHAMMER_METADATA },
    RegisteredMetadata { slug: "cdlkickingbylength", meta: &CDLKICKINGBYLENGTH_METADATA },
    RegisteredMetadata { slug: "cdlkicking", meta: &CDLKICKING_METADATA },
    RegisteredMetadata { slug: "cdlladderbottom", meta: &CDLLADDERBOTTOM_METADATA },
    RegisteredMetadata { slug: "cdllongleggeddoji", meta: &CDLLONGLEGGEDDOJI_METADATA },
    RegisteredMetadata { slug: "cdllongline", meta: &CDLLONGLINE_METADATA },
    RegisteredMetadata { slug: "cdlmarubozu", meta: &CDLMARUBOZU_METADATA },
    RegisteredMetadata { slug: "cdlmatchinglow", meta: &CDLMATCHINGLOW_METADATA },
    RegisteredMetadata { slug: "cdlmathold", meta: &CDLMATHOLD_METADATA },
    RegisteredMetadata { slug: "cdlmorningdojistar", meta: &CDLMORNINGDOJISTAR_METADATA },
    RegisteredMetadata { slug: "cdlmorningstar", meta: &CDLMORNINGSTAR_METADATA },
    RegisteredMetadata { slug: "cdlonneck", meta: &CDLONNECK_METADATA },
    RegisteredMetadata { slug: "cdlpiercing", meta: &CDLPIERCING_METADATA },
    RegisteredMetadata { slug: "cdlrickshawman", meta: &CDLRICKSHAWMAN_METADATA },
    RegisteredMetadata { slug: "cdlrisefall3methods", meta: &CDLRISEFALL3METHODS_METADATA },
    RegisteredMetadata { slug: "cdlseparatinglines", meta: &CDLSEPARATINGLINES_METADATA },
    RegisteredMetadata { slug: "cdlshootingstar", meta: &CDLSHOOTINGSTAR_METADATA },
    RegisteredMetadata { slug: "cdlshortline", meta: &CDLSHORTLINE_METADATA },
    RegisteredMetadata { slug: "cdlspinningtop", meta: &CDLSPINNINGTOP_METADATA },
    RegisteredMetadata { slug: "cdlstalledpattern", meta: &CDLSTALLEDPATTERN_METADATA },
    RegisteredMetadata { slug: "cdlsticksandwich", meta: &CDLSTICKSANDWICH_METADATA },
    RegisteredMetadata { slug: "cdltakuri", meta: &CDLTAKURI_METADATA },
    RegisteredMetadata { slug: "cdltasukigap", meta: &CDLTASUKIGAP_METADATA },
    RegisteredMetadata { slug: "cdlthrusting", meta: &CDLTHRUSTING_METADATA },
    RegisteredMetadata { slug: "cdltristar", meta: &CDLTRISTAR_METADATA },
    RegisteredMetadata { slug: "cdlunique3river", meta: &CDLUNIQUE3RIVER_METADATA },
    RegisteredMetadata { slug: "cdlupsidegap2crows", meta: &CDLUPSIDEGAP2CROWS_METADATA },
    RegisteredMetadata { slug: "cdlxsidegap3methods", meta: &CDLXSIDEGAP3METHODS_METADATA },
    RegisteredMetadata { slug: "cg", meta: &CG_METADATA },
    RegisteredMetadata { slug: "channel_cycle", meta: &CHANNEL_CYCLE_METADATA },
    RegisteredMetadata { slug: "choppiness_index", meta: &CHOPPINESS_INDEX_METADATA },
    RegisteredMetadata { slug: "classic_laguerre", meta: &CLASSIC_LAGUERRE_METADATA },
    RegisteredMetadata { slug: "cmo", meta: &CMO_METADATA },
    RegisteredMetadata { slug: "continuation_index", meta: &CONTINUATION_INDEX_METADATA },
    RegisteredMetadata { slug: "correlation_cycle", meta: &CORRELATION_CYCLE_METADATA },
    RegisteredMetadata { slug: "correlation_trend", meta: &CORRELATION_TREND_METADATA },
    RegisteredMetadata { slug: "correl", meta: &CORREL_METADATA },
    RegisteredMetadata { slug: "cybernetic_oscillator", meta: &CYBERNETIC_OSCILLATOR_METADATA },
    RegisteredMetadata { slug: "cyber_cycle", meta: &CYBER_CYCLE_METADATA },
    RegisteredMetadata { slug: "cycle_trend_analytics", meta: &CYCLE_TREND_ANALYTICS_METADATA },
    RegisteredMetadata { slug: "dema", meta: &DEMA_METADATA },
    RegisteredMetadata { slug: "dmh", meta: &DMH_METADATA },
    RegisteredMetadata { slug: "donchian", meta: &DONCHIAN_METADATA },
    RegisteredMetadata { slug: "dsma", meta: &DSMA_METADATA },
    RegisteredMetadata { slug: "ehlers_autocorrelation", meta: &EHLERS_AUTOCORRELATION_METADATA },
    RegisteredMetadata { slug: "ehlers_filter", meta: &EHLERS_FILTER_METADATA },
    RegisteredMetadata { slug: "ehlers_loops", meta: &EHLERS_LOOPS_METADATA },
    RegisteredMetadata { slug: "ehlers_stochastic", meta: &EHLERS_STOCHASTIC_METADATA },
    RegisteredMetadata { slug: "ehlers_ultimate_oscillator", meta: &EHLERS_ULTIMATE_OSCILLATOR_METADATA },
    RegisteredMetadata { slug: "ema", meta: &EMA_METADATA },
    RegisteredMetadata { slug: "emd", meta: &EMD_METADATA },
    RegisteredMetadata { slug: "fisher_high_pass", meta: &FISHER_HIGH_PASS_METADATA },
    RegisteredMetadata { slug: "fisher", meta: &FISHER_METADATA },
    RegisteredMetadata { slug: "fm_demodulator", meta: &FM_DEMODULATOR_METADATA },
    RegisteredMetadata { slug: "fourier_dominant_cycle", meta: &FOURIER_DOMINANT_CYCLE_METADATA },
    RegisteredMetadata { slug: "fourier_series_model", meta: &FOURIER_SERIES_MODEL_METADATA },
    RegisteredMetadata { slug: "fractals", meta: &FRACTALS_METADATA },
    RegisteredMetadata { slug: "frama", meta: &FRAMA_METADATA },
    RegisteredMetadata { slug: "gap_momentum", meta: &GAP_MOMENTUM_METADATA },
    RegisteredMetadata { slug: "gaussian_filter", meta: &GAUSSIAN_FILTER_METADATA },
    RegisteredMetadata { slug: "generalized_laguerre", meta: &GENERALIZED_LAGUERRE_METADATA },
    RegisteredMetadata { slug: "geometric_patterns", meta: &GEOMETRIC_PATTERNS_METADATA },
    RegisteredMetadata { slug: "griffiths_dominant_cycle", meta: &GRIFFITHS_DOMINANT_CYCLE_METADATA },
    RegisteredMetadata { slug: "griffiths_predictor", meta: &GRIFFITHS_PREDICTOR_METADATA },
    RegisteredMetadata { slug: "griffiths_spectrum", meta: &GRIFFITHS_SPECTRUM_METADATA },
    RegisteredMetadata { slug: "hamming_filter", meta: &HAMMING_FILTER_METADATA },
    RegisteredMetadata { slug: "hann_filter", meta: &HANN_FILTER_METADATA },
    RegisteredMetadata { slug: "harrington_adx", meta: &HARRINGTON_ADX_METADATA },
    RegisteredMetadata { slug: "heikin_ashi", meta: &HEIKIN_ASHI_METADATA },
    RegisteredMetadata { slug: "high_pass", meta: &HIGH_PASS_METADATA },
    RegisteredMetadata { slug: "hma", meta: &HMA_METADATA },
    RegisteredMetadata { slug: "homodyne_discriminator", meta: &HOMODYNE_DISCRIMINATOR_METADATA },
    RegisteredMetadata { slug: "ht_dcperiod", meta: &HT_DCPERIOD_METADATA },
    RegisteredMetadata { slug: "ht_dcphase", meta: &HT_DCPHASE_METADATA },
    RegisteredMetadata { slug: "ht_phasor", meta: &HT_PHASOR_METADATA },
    RegisteredMetadata { slug: "ht_sine", meta: &HT_SINE_METADATA },
    RegisteredMetadata { slug: "ht_trendmode", meta: &HT_TRENDMODE_METADATA },
    RegisteredMetadata { slug: "hurst_exponent", meta: &HURST_EXPONENT_METADATA },
    RegisteredMetadata { slug: "ichimoku", meta: &ICHIMOKU_METADATA },
    RegisteredMetadata { slug: "instantaneous_trendline", meta: &INSTANTANEOUS_TRENDLINE_METADATA },
    RegisteredMetadata { slug: "inverse_fisher", meta: &INVERSE_FISHER_METADATA },
    RegisteredMetadata { slug: "kalman_filter", meta: &KALMAN_FILTER_METADATA },
    RegisteredMetadata { slug: "kama", meta: &KAMA_METADATA },
    RegisteredMetadata { slug: "keltner", meta: &KELTNER_METADATA },
    RegisteredMetadata { slug: "kinematic_kalman", meta: &KINEMATIC_KALMAN_METADATA },
    RegisteredMetadata { slug: "laguerre_filter", meta: &LAGUERRE_FILTER_METADATA },
    RegisteredMetadata { slug: "laguerre_oscillator", meta: &LAGUERRE_OSCILLATOR_METADATA },
    RegisteredMetadata { slug: "laguerre_rsi", meta: &LAGUERRE_RSI_METADATA },
    RegisteredMetadata { slug: "linreg", meta: &LINREG_METADATA },
    RegisteredMetadata { slug: "macd", meta: &MACD_METADATA },
    RegisteredMetadata { slug: "madh", meta: &MADH_METADATA },
    RegisteredMetadata { slug: "mad", meta: &MAD_METADATA },
    RegisteredMetadata { slug: "mama", meta: &MAMA_METADATA },
    RegisteredMetadata { slug: "market_state", meta: &MARKET_STATE_METADATA },
    RegisteredMetadata { slug: "market_structure", meta: &MARKET_STRUCTURE_METADATA },
    RegisteredMetadata { slug: "medprice", meta: &MEDPRICE_METADATA },
    RegisteredMetadata { slug: "mesa_stochastic", meta: &MESA_STOCHASTIC_METADATA },
    RegisteredMetadata { slug: "mfi", meta: &MFI_METADATA },
    RegisteredMetadata { slug: "mom", meta: &MOM_METADATA },
    RegisteredMetadata { slug: "my_rsi", meta: &MY_RSI_METADATA },
    RegisteredMetadata { slug: "natr", meta: &NATR_METADATA },
    RegisteredMetadata { slug: "noise_elimination", meta: &NOISE_ELIMINATION_METADATA },
    RegisteredMetadata { slug: "obv", meta: &OBV_METADATA },
    RegisteredMetadata { slug: "oc2", meta: &OC2_METADATA },
    RegisteredMetadata { slug: "oc_price_rsi", meta: &OC_PRICE_RSI_METADATA },
    RegisteredMetadata { slug: "one_euro_filter", meta: &ONE_EURO_FILTER_METADATA },
    RegisteredMetadata { slug: "pairs_rotation", meta: &PAIRS_ROTATION_METADATA },
    RegisteredMetadata { slug: "phasor", meta: &PHASOR_METADATA },
    RegisteredMetadata { slug: "pivot_points", meta: &PIVOT_POINTS_METADATA },
    RegisteredMetadata { slug: "ppo", meta: &PPO_METADATA },
    RegisteredMetadata { slug: "precision_trend_analysis", meta: &PRECISION_TREND_ANALYSIS_METADATA },
    RegisteredMetadata { slug: "projected_moving_average", meta: &PROJECTED_MOVING_AVERAGE_METADATA },
    RegisteredMetadata { slug: "recursive_median", meta: &RECURSIVE_MEDIAN_METADATA },
    RegisteredMetadata { slug: "recursive_median_oscillator", meta: &RECURSIVE_MEDIAN_OSCILLATOR_METADATA },
    RegisteredMetadata { slug: "reflex", meta: &REFLEX_METADATA },
    RegisteredMetadata { slug: "reverse_ema", meta: &REVERSE_EMA_METADATA },
    RegisteredMetadata { slug: "reversion_index", meta: &REVERSION_INDEX_METADATA },
    RegisteredMetadata { slug: "rocket_rsi", meta: &ROCKET_RSI_METADATA },
    RegisteredMetadata { slug: "roc", meta: &ROC_METADATA },
    RegisteredMetadata { slug: "roofing_filter", meta: &ROOFING_FILTER_METADATA },
    RegisteredMetadata { slug: "rsih", meta: &RSIH_METADATA },
    RegisteredMetadata { slug: "rsi", meta: &RSI_METADATA },
    RegisteredMetadata { slug: "sar", meta: &SAR_METADATA },
    RegisteredMetadata { slug: "sdo", meta: &SDO_METADATA },
    RegisteredMetadata { slug: "simple_predictor", meta: &SIMPLE_PREDICTOR_METADATA },
    RegisteredMetadata { slug: "sine_wave", meta: &SINE_WAVE_METADATA },
    RegisteredMetadata { slug: "sma", meta: &SMA_METADATA },
    RegisteredMetadata { slug: "sr_interaction_monitor", meta: &SR_INTERACTION_MONITOR_METADATA },
    RegisteredMetadata { slug: "stc", meta: &STC_METADATA },
    RegisteredMetadata { slug: "stddev", meta: &STDDEV_METADATA },
    RegisteredMetadata { slug: "stoch", meta: &STOCH_METADATA },
    RegisteredMetadata { slug: "super_smoother", meta: &SUPER_SMOOTHER_METADATA },
    RegisteredMetadata { slug: "swiss_army_knife", meta: &SWISS_ARMY_KNIFE_METADATA },
    RegisteredMetadata { slug: "synthetic_oscillator", meta: &SYNTHETIC_OSCILLATOR_METADATA },
    RegisteredMetadata { slug: "system_evaluator", meta: &SYSTEM_EVALUATOR_METADATA },
    RegisteredMetadata { slug: "t3", meta: &T3_METADATA },
    RegisteredMetadata { slug: "tema", meta: &TEMA_METADATA },
    RegisteredMetadata { slug: "tradj_ema", meta: &TRADJ_EMA_METADATA },
    RegisteredMetadata { slug: "trendflex", meta: &TRENDFLEX_METADATA },
    RegisteredMetadata { slug: "triangle_filter", meta: &TRIANGLE_FILTER_METADATA },
    RegisteredMetadata { slug: "trima", meta: &TRIMA_METADATA },
    RegisteredMetadata { slug: "trix", meta: &TRIX_METADATA },
    RegisteredMetadata { slug: "true_range", meta: &TRUE_RANGE_METADATA },
    RegisteredMetadata { slug: "truncated_bandpass", meta: &TRUNCATED_BANDPASS_METADATA },
    RegisteredMetadata { slug: "ttm_squeeze", meta: &TTM_SQUEEZE_METADATA },
    RegisteredMetadata { slug: "typprice", meta: &TYPPRICE_METADATA },
    RegisteredMetadata { slug: "ultimate_bands", meta: &ULTIMATE_BANDS_METADATA },
    RegisteredMetadata { slug: "ultimate_channel", meta: &ULTIMATE_CHANNEL_METADATA },
    RegisteredMetadata { slug: "ultimate_smoother", meta: &ULTIMATE_SMOOTHER_METADATA },
    RegisteredMetadata { slug: "ultosc", meta: &ULTOSC_METADATA },
    RegisteredMetadata { slug: "undersampled_double_ma", meta: &UNDERSAMPLED_DOUBLE_MA_METADATA },
    RegisteredMetadata { slug: "universal_oscillator", meta: &UNIVERSAL_OSCILLATOR_METADATA },
    RegisteredMetadata { slug: "usi", meta: &USI_METADATA },
    RegisteredMetadata { slug: "volume_profile", meta: &VOLUME_PROFILE_METADATA },
    RegisteredMetadata { slug: "vortex", meta: &VORTEX_METADATA },
    RegisteredMetadata { slug: "voss_predictor", meta: &VOSS_PREDICTOR_METADATA },
    RegisteredMetadata { slug: "vpn", meta: &VPN_METADATA },
    RegisteredMetadata { slug: "vwap", meta: &VWAP_METADATA },
    RegisteredMetadata { slug: "wavetrend", meta: &WAVETREND_METADATA },
    RegisteredMetadata { slug: "wclprice", meta: &WCLPRICE_METADATA },
    RegisteredMetadata { slug: "willr", meta: &WILLR_METADATA },
    RegisteredMetadata { slug: "wma", meta: &WMA_METADATA },
    RegisteredMetadata { slug: "zero_lag", meta: &ZERO_LAG_METADATA },
    RegisteredMetadata { slug: "zlema", meta: &ZLEMA_METADATA },
];

/// Flat view of metadata pointers (legacy / export).
pub static ALL_INDICATOR_METADATA: &[&IndicatorMetadata] = &[
    &ADAPTIVE_EMA_METADATA,
    &ADOSC_METADATA,
    &ADX_METADATA,
    &AD_METADATA,
    &ALLIGATOR_METADATA,
    &ALMA_METADATA,
    &AM_DETECTOR_METADATA,
    &APO_METADATA,
    &AROON_METADATA,
    &ATR_METADATA,
    &ATR_TS_METADATA,
    &AUTOTUNE_FILTER_METADATA,
    &AVGPRICE_METADATA,
    &BANDPASS_METADATA,
    &BBANDS_METADATA,
    &BETA_METADATA,
    &BUTTERWORTH2_METADATA,
    &BUTTERWORTH3_METADATA,
    &CCI_METADATA,
    &CDL2CROWS_METADATA,
    &CDL3BLACKCROWS_METADATA,
    &CDL3INSIDE_METADATA,
    &CDL3LINESTRIKE_METADATA,
    &CDL3OUTSIDE_METADATA,
    &CDL3STARSINSOUTH_METADATA,
    &CDL3WHITESOLDIERS_METADATA,
    &CDLABANDONEDBABY_METADATA,
    &CDLADVANCEBLOCK_METADATA,
    &CDLBELTHOLD_METADATA,
    &CDLBREAKAWAY_METADATA,
    &CDLCLOSINGMARUBOZU_METADATA,
    &CDLCONCEALBABYSWALL_METADATA,
    &CDLCOUNTERATTACK_METADATA,
    &CDLDARKCLOUDCOVER_METADATA,
    &CDLDOJISTAR_METADATA,
    &CDLDOJI_METADATA,
    &CDLDRAGONFLYDOJI_METADATA,
    &CDLENGULFING_METADATA,
    &CDLEVENINGDOJISTAR_METADATA,
    &CDLEVENINGSTAR_METADATA,
    &CDLGAPSIDESIDEWHITE_METADATA,
    &CDLGRAVESTONEDOJI_METADATA,
    &CDLHAMMER_METADATA,
    &CDLHANGINGMAN_METADATA,
    &CDLHARAMICROSS_METADATA,
    &CDLHARAMI_METADATA,
    &CDLHIGHWAVE_METADATA,
    &CDLHIKKAKEMOD_METADATA,
    &CDLHIKKAKE_METADATA,
    &CDLHOMINGPIGEON_METADATA,
    &CDLIDENTICAL3CROWS_METADATA,
    &CDLINNECK_METADATA,
    &CDLINVERTEDHAMMER_METADATA,
    &CDLKICKINGBYLENGTH_METADATA,
    &CDLKICKING_METADATA,
    &CDLLADDERBOTTOM_METADATA,
    &CDLLONGLEGGEDDOJI_METADATA,
    &CDLLONGLINE_METADATA,
    &CDLMARUBOZU_METADATA,
    &CDLMATCHINGLOW_METADATA,
    &CDLMATHOLD_METADATA,
    &CDLMORNINGDOJISTAR_METADATA,
    &CDLMORNINGSTAR_METADATA,
    &CDLONNECK_METADATA,
    &CDLPIERCING_METADATA,
    &CDLRICKSHAWMAN_METADATA,
    &CDLRISEFALL3METHODS_METADATA,
    &CDLSEPARATINGLINES_METADATA,
    &CDLSHOOTINGSTAR_METADATA,
    &CDLSHORTLINE_METADATA,
    &CDLSPINNINGTOP_METADATA,
    &CDLSTALLEDPATTERN_METADATA,
    &CDLSTICKSANDWICH_METADATA,
    &CDLTAKURI_METADATA,
    &CDLTASUKIGAP_METADATA,
    &CDLTHRUSTING_METADATA,
    &CDLTRISTAR_METADATA,
    &CDLUNIQUE3RIVER_METADATA,
    &CDLUPSIDEGAP2CROWS_METADATA,
    &CDLXSIDEGAP3METHODS_METADATA,
    &CG_METADATA,
    &CHANNEL_CYCLE_METADATA,
    &CHOPPINESS_INDEX_METADATA,
    &CLASSIC_LAGUERRE_METADATA,
    &CMO_METADATA,
    &CONTINUATION_INDEX_METADATA,
    &CORRELATION_CYCLE_METADATA,
    &CORRELATION_TREND_METADATA,
    &CORREL_METADATA,
    &CYBERNETIC_OSCILLATOR_METADATA,
    &CYBER_CYCLE_METADATA,
    &CYCLE_TREND_ANALYTICS_METADATA,
    &DEMA_METADATA,
    &DMH_METADATA,
    &DONCHIAN_METADATA,
    &DSMA_METADATA,
    &EHLERS_AUTOCORRELATION_METADATA,
    &EHLERS_FILTER_METADATA,
    &EHLERS_LOOPS_METADATA,
    &EHLERS_STOCHASTIC_METADATA,
    &EHLERS_ULTIMATE_OSCILLATOR_METADATA,
    &EMA_METADATA,
    &EMD_METADATA,
    &FISHER_HIGH_PASS_METADATA,
    &FISHER_METADATA,
    &FM_DEMODULATOR_METADATA,
    &FOURIER_DOMINANT_CYCLE_METADATA,
    &FOURIER_SERIES_MODEL_METADATA,
    &FRACTALS_METADATA,
    &FRAMA_METADATA,
    &GAP_MOMENTUM_METADATA,
    &GAUSSIAN_FILTER_METADATA,
    &GENERALIZED_LAGUERRE_METADATA,
    &GEOMETRIC_PATTERNS_METADATA,
    &GRIFFITHS_DOMINANT_CYCLE_METADATA,
    &GRIFFITHS_PREDICTOR_METADATA,
    &GRIFFITHS_SPECTRUM_METADATA,
    &HAMMING_FILTER_METADATA,
    &HANN_FILTER_METADATA,
    &HARRINGTON_ADX_METADATA,
    &HEIKIN_ASHI_METADATA,
    &HIGH_PASS_METADATA,
    &HMA_METADATA,
    &HOMODYNE_DISCRIMINATOR_METADATA,
    &HT_DCPERIOD_METADATA,
    &HT_DCPHASE_METADATA,
    &HT_PHASOR_METADATA,
    &HT_SINE_METADATA,
    &HT_TRENDMODE_METADATA,
    &HURST_EXPONENT_METADATA,
    &ICHIMOKU_METADATA,
    &INSTANTANEOUS_TRENDLINE_METADATA,
    &INVERSE_FISHER_METADATA,
    &KALMAN_FILTER_METADATA,
    &KAMA_METADATA,
    &KELTNER_METADATA,
    &KINEMATIC_KALMAN_METADATA,
    &LAGUERRE_FILTER_METADATA,
    &LAGUERRE_OSCILLATOR_METADATA,
    &LAGUERRE_RSI_METADATA,
    &LINREG_METADATA,
    &MACD_METADATA,
    &MADH_METADATA,
    &MAD_METADATA,
    &MAMA_METADATA,
    &MARKET_STATE_METADATA,
    &MARKET_STRUCTURE_METADATA,
    &MEDPRICE_METADATA,
    &MESA_STOCHASTIC_METADATA,
    &MFI_METADATA,
    &MOM_METADATA,
    &MY_RSI_METADATA,
    &NATR_METADATA,
    &NOISE_ELIMINATION_METADATA,
    &OBV_METADATA,
    &OC2_METADATA,
    &OC_PRICE_RSI_METADATA,
    &ONE_EURO_FILTER_METADATA,
    &PAIRS_ROTATION_METADATA,
    &PHASOR_METADATA,
    &PIVOT_POINTS_METADATA,
    &PPO_METADATA,
    &PRECISION_TREND_ANALYSIS_METADATA,
    &PROJECTED_MOVING_AVERAGE_METADATA,
    &RECURSIVE_MEDIAN_METADATA,
    &RECURSIVE_MEDIAN_OSCILLATOR_METADATA,
    &REFLEX_METADATA,
    &REVERSE_EMA_METADATA,
    &REVERSION_INDEX_METADATA,
    &ROCKET_RSI_METADATA,
    &ROC_METADATA,
    &ROOFING_FILTER_METADATA,
    &RSIH_METADATA,
    &RSI_METADATA,
    &SAR_METADATA,
    &SDO_METADATA,
    &SIMPLE_PREDICTOR_METADATA,
    &SINE_WAVE_METADATA,
    &SMA_METADATA,
    &SR_INTERACTION_MONITOR_METADATA,
    &STC_METADATA,
    &STDDEV_METADATA,
    &STOCH_METADATA,
    &SUPER_SMOOTHER_METADATA,
    &SWISS_ARMY_KNIFE_METADATA,
    &SYNTHETIC_OSCILLATOR_METADATA,
    &SYSTEM_EVALUATOR_METADATA,
    &T3_METADATA,
    &TEMA_METADATA,
    &TRADJ_EMA_METADATA,
    &TRENDFLEX_METADATA,
    &TRIANGLE_FILTER_METADATA,
    &TRIMA_METADATA,
    &TRIX_METADATA,
    &TRUE_RANGE_METADATA,
    &TRUNCATED_BANDPASS_METADATA,
    &TTM_SQUEEZE_METADATA,
    &TYPPRICE_METADATA,
    &ULTIMATE_BANDS_METADATA,
    &ULTIMATE_CHANNEL_METADATA,
    &ULTIMATE_SMOOTHER_METADATA,
    &ULTOSC_METADATA,
    &UNDERSAMPLED_DOUBLE_MA_METADATA,
    &UNIVERSAL_OSCILLATOR_METADATA,
    &USI_METADATA,
    &VOLUME_PROFILE_METADATA,
    &VORTEX_METADATA,
    &VOSS_PREDICTOR_METADATA,
    &VPN_METADATA,
    &VWAP_METADATA,
    &WAVETREND_METADATA,
    &WCLPRICE_METADATA,
    &WILLR_METADATA,
    &WMA_METADATA,
    &ZERO_LAG_METADATA,
    &ZLEMA_METADATA,
];

pub const METADATA_COUNT: usize = 216;
