talib_1_in_1_out!(RSI, talib_rs::momentum::rsi, timeperiod: usize);
talib_1_in_3_out!(MACD, talib_rs::momentum::macd, fastperiod: usize, slowperiod: usize, signalperiod: usize);
talib_1_in_3_out!(MACDEXT, talib_rs::momentum::macd_ext, fastperiod: usize, fastmatype: talib_rs::MaType, slowperiod: usize, slowmatype: talib_rs::MaType, signalperiod: usize, signalmatype: talib_rs::MaType);
talib_1_in_3_out!(MACDFIX, talib_rs::momentum::macd_fix, signalperiod: usize);

talib_3_in_2_out!(STOCH, talib_rs::momentum::stoch, fastk_period: usize, slowk_period: usize, slowk_matype: talib_rs::MaType, slowd_period: usize, slowd_matype: talib_rs::MaType);
talib_3_in_2_out!(STOCHF, talib_rs::momentum::stochf, fastk_period: usize, fastd_period: usize, fastd_matype: talib_rs::MaType);
talib_1_in_2_out!(STOCHRSI, talib_rs::momentum::stochrsi, timeperiod: usize, fastk_period: usize, fastd_period: usize, fastd_matype: talib_rs::MaType);

talib_3_in_1_out!(ADX, talib_rs::momentum::adx, timeperiod: usize);
talib_3_in_1_out!(ADXR, talib_rs::momentum::adxr, timeperiod: usize);
talib_3_in_1_out!(CCI, talib_rs::momentum::cci, timeperiod: usize);
talib_1_in_1_out!(MOM, talib_rs::momentum::mom, timeperiod: usize);
talib_1_in_1_out!(ROC, talib_rs::momentum::roc, timeperiod: usize);
talib_1_in_1_out!(ROCP, talib_rs::momentum::rocp, timeperiod: usize);
talib_1_in_1_out!(ROCR, talib_rs::momentum::rocr, timeperiod: usize);
talib_1_in_1_out!(ROCR100, talib_rs::momentum::rocr100, timeperiod: usize);
talib_3_in_1_out!(WILLR, talib_rs::momentum::willr, timeperiod: usize);
talib_1_in_1_out!(APO, talib_rs::momentum::apo, fastperiod: usize, slowperiod: usize, matype: talib_rs::MaType);
talib_1_in_1_out!(PPO, talib_rs::momentum::ppo, fastperiod: usize, slowperiod: usize, matype: talib_rs::MaType);
talib_4_in_1_out!(BOP, talib_rs::momentum::bop);
talib_1_in_1_out!(CMO, talib_rs::momentum::cmo, timeperiod: usize);
talib_2_in_2_out!(AROON, talib_rs::momentum::aroon, timeperiod: usize);
talib_2_in_1_out!(AROONOSC, talib_rs::momentum::aroon_osc, timeperiod: usize);
talib_4_in_1_out!(MFI, talib_rs::momentum::mfi, timeperiod: usize);
talib_1_in_1_out!(TRIX, talib_rs::momentum::trix, timeperiod: usize);
talib_3_in_1_out!(ULTOSC, talib_rs::momentum::ultosc, timeperiod1: usize, timeperiod2: usize, timeperiod3: usize);
talib_3_in_1_out!(DX, talib_rs::momentum::dx, timeperiod: usize);
talib_3_in_1_out!(PLUS_DI, talib_rs::momentum::plus_di, timeperiod: usize);
talib_3_in_1_out!(MINUS_DI, talib_rs::momentum::minus_di, timeperiod: usize);
talib_2_in_1_out!(PLUS_DM, talib_rs::momentum::plus_dm, timeperiod: usize);
talib_2_in_1_out!(MINUS_DM, talib_rs::momentum::minus_dm, timeperiod: usize);
