#!/usr/bin/env python3
"""Generate quantwave-core/src/indicators/metadata_registry.rs from *_METADATA constants."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDICATORS_DIR = ROOT / "quantwave-core" / "src" / "indicators"
REGIMES_DIR = ROOT / "quantwave-core" / "src" / "regimes"
OUT = INDICATORS_DIR / "metadata_registry.rs"
SCAN_DIRS = (INDICATORS_DIR, REGIMES_DIR)

CONST_RE = re.compile(r"pub const (\w+_METADATA): IndicatorMetadata")


def module_path(rust_file: Path) -> str:
    if rust_file.is_relative_to(INDICATORS_DIR):
        base = "crate::indicators::"
        rel = rust_file.relative_to(INDICATORS_DIR)
    else:
        base = "crate::regimes::"
        rel = rust_file.relative_to(REGIMES_DIR)
    parts = list(rel.parts)
    if parts[-1] == "mod.rs":
        parts = parts[:-1]
    else:
        parts[-1] = parts[-1].removesuffix(".rs")
    return base + "::".join(parts)


def collect_entries() -> list[tuple[str, str, str, str]]:
    entries: list[tuple[str, str, str, str]] = []
    for scan_dir in SCAN_DIRS:
        for path in sorted(scan_dir.rglob("*.rs")):
            if path.name == "metadata_registry.rs":
                continue
            text = path.read_text(encoding="utf-8")
            source_stem = path.stem
            # Extract default struct for the file
            file_struct_m = re.search(r"pub struct (\w+)", text)
            file_struct = file_struct_m.group(1) if file_struct_m else ""

            for const_name in CONST_RE.findall(text):
                struct_name = const_name.removesuffix("_METADATA")
                potential_struct = "".join(x.capitalize() for x in struct_name.lower().split('_'))
                if re.search(rf"pub struct {potential_struct}", text, re.IGNORECASE):
                    struct_name = potential_struct
                else:
                    struct_name = file_struct

                entries.append((module_path(path), const_name, struct_name, source_stem))

    # stable dedupe by const name
    seen: set[str] = set()
    unique: list[tuple[str, str, str, str]] = []
    for mod_path, const_name, struct_name, source_stem in entries:
        if const_name in seen:
            continue
        seen.add(const_name)
        unique.append((mod_path, const_name, struct_name, source_stem))
    return sorted(unique, key=lambda x: x[1])


def slug_from_const(const_name: str) -> str:
    base = const_name.removesuffix("_METADATA")
    return base.lower()


def render(entries: list[tuple[str, str, str, str]]) -> str:
    use_lines = sorted({f"use {mod_path}::{const_name};" for mod_path, const_name, _, _ in entries})
    registered = "\n    ".join(
        f'RegisteredMetadata {{ slug: "{slug_from_const(c)}", meta: &{c}, struct_name: "{s}", source_file: "{stem}" }},'
        for _, c, s, stem in entries
    )
    refs = "\n    ".join(f"&{const_name}," for _, const_name, _, _ in entries)
    return f"""//! AUTO-GENERATED by scripts/regenerate_metadata_registry.py — do not edit by hand.
//! Re-run: `python scripts/regenerate_metadata_registry.py`

use super::metadata::IndicatorMetadata;

{chr(10).join(use_lines)}

/// Slug + metadata pair for codegen and discovery.
#[derive(Debug, Clone, Copy)]
pub struct RegisteredMetadata {{
    pub slug: &'static str,
    pub meta: &'static IndicatorMetadata,
    pub struct_name: &'static str,
    pub source_file: &'static str,
}}

/// All registered indicator metadata (slug is Python/API key derived from const name).
pub static ALL_REGISTERED: &[RegisteredMetadata] = &[
    {registered}
];

/// Flat view of metadata pointers (legacy / export).
pub static ALL_INDICATOR_METADATA: &[&IndicatorMetadata] = &[
    {refs}
];

pub const METADATA_COUNT: usize = {len(entries)};
"""


def main() -> None:
    entries = collect_entries()
    OUT.write_text(render(entries), encoding="utf-8")
    print(f"Wrote {len(entries)} metadata entries to {OUT}")


if __name__ == "__main__":
    main()