[book]
authors = ["Mayank Lavania"]
language = "en"
src = "src"
title = "QuantWave Documentation"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/lavs9/quantwave"
additional-css = ["theme/catppuccin.css", "theme/indicator-badges.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
